# Laboratorio 1 (Admin Pasiva Vs Admin Activa)
    
## Equipo E

Ana Paula Rangel
Paulina Rodriguez
Jose Suáres
Diego Velasco


    Laboratorio 1: Administración activa Vs Administración pasiva del capital.
    Recuerda que la fecha de ésta es la última en la cual puedes realizar modificaciones en repositorio del laboratorio. Este espacio sólo es para subir evidencia del laboratorio, la revisión oficial del contenido la haré siempre desde el repositorio.

    Sobre este laboratorio:
    - El propósito: Que puedas explicar las diferencias cuantitativas y cualitativas de administrar activamente o pasivamente el capital. Utilizando el caso de los ETFs con posiciones en acciones, para el caso particular de IShares y ETFs cuyos activos coticen en bolsas de valores de USA.

    Recuerda que:
    - En este espacio debes de subir el jupyter notebook de la versión final.

    - Todos los integrantes del equipo deben de subir el mismo archivo.

    - El nombre del archivo debe de ser como sigue: equipo_myst_laboratorio1

    Ejemplo, para el equipo "A", el nombre del archivo que deben de subir es A_myst_laboratorio1.ipynb
    
    https://www.quandl.com/search?filters=%5B%22Mutual%20Funds%20%26%20ETFs%22%2C%22Free%22%2C%22United%20States%22%5D

## ETF 

https://www.ishares.com/us/products/239774/ishares-core-sp-smallcap-etf

sacar rendimientos mensuales
sacar la desviacion estandar para tener la volatilidad de esta es diaria entonces es la desviacion de los rendiminetos diarios
 tenemos 12 meses, pero no se modifican ni el priemro ni el ultimo
 con el peso calculamos la varianza
 desviacion de cada mes usando la desviacion de los diarios
 
 1. descargar los datos mensusuales de un año
 2. rendimientos diario y la desv estandar y el sharp (tasa lubre de riegso usa, treasury hold)
 3. Net asset value diario es l NAV (el precio diario de tu ETF) este sirve para sacar la volatilidad y ver si hubo picos si no hay esta muy tranquio (rendimientos diarios por los pesos mensuales para sacar el diario)--> de los 13 archivos
 4. hacer 11 escenarios diferentes para ver cual habria sido la mejorstuacion
 
 3 escenarios
 A-> Todo el año con los primeros pesos
 B-> Rebalancear igual que el ETF
 C-> Rebalancear cada mes

### Importar librerias

In [8]:
import quandl
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt

### Descargar precios diarios de Quandl

In [10]:
# The Tiker
etf_w1=pd.read_csv("https://raw.githubusercontent.com/anapaurangel/MyST/master/Data/Enero18.csv")
tiker=etf_w1[:-2]
tiker

#Daily stock prices
quandl.ApiConfig.api_key = 'wzJyeSB_seJSjER5FGSA'
quandl_data = quandl.get_table('WIKI/PRICES',qopts = { 'columns': ['ticker', 'date', "Open",'adj_close'] }, 
                        date = { 'gte': '2017-02-28', 'lte': '2018-02-28' }, 
                        paginate=True)
quandl_data.head()

     ticker       date   open  adj_close
None
0      ZUMZ 2018-02-28  20.00      19.70
1      ZUMZ 2018-02-27  20.70      19.80
2      ZUMZ 2018-02-26  20.35      20.55
3      ZUMZ 2018-02-23  19.90      20.25
4      ZUMZ 2018-02-22  19.55      19.80

In [11]:
#Table to work in the data 
daily_data = quandl_data.set_index('date')
daily_data = daily_data.pivot(columns='ticker')
daily_data

             open                                                       \
ticker          A     AA    AAL     AAMC    AAN   AAOI   AAON      AAP
date
2017-02-28  51.52  34.73  46.32  69.6000  27.16  47.56  34.00  155.640
2017-03-01  51.62  35.93  46.79  71.3000  27.50  46.42  34.10  158.590
2017-03-02  52.04  37.64  46.67  74.4500  27.72  46.97  35.20  156.680
2017-03-03  51.38  36.06  45.85  79.0500  28.06  50.00  35.50  157.300
2017-03-06  51.64  36.80  46.41  85.6500  27.83  52.75  35.00  155.350
2017-03-07  51.06  36.81  45.02  80.4000  27.40  51.31  34.60  154.260
2017-03-08  51.26  35.90  44.79  77.9500  27.27  54.85  35.00  153.510
2017-03-09  51.42  36.07  44.50  74.1500  27.53  52.44  34.85  154.970
2017-03-10  51.69  35.90  43.46  75.9000  27.44  52.01  35.15  155.520
2017-03-13  52.14  35.21  43.73  77.0000  28.07  51.15  35.30  152.760
2017-03-14  52.24  34.45  42.06  74.6000  28.40  50.57  35.10  154.300
2017-03-15  53.31  34.40  40.50  74.9500  28.91  48.27  35.60  153.580
2017-03-16  53.43  35.66  42.18  74.9000  29.55  47.80  36.20  152.740
2017-03-17  53.06  35.57  42.00  73.4500  30.05  48.00  36.60  152.420
2017-03-20  53.33  34.90  42.18  63.3500  30.05  51.37  36.85  152.950
2017-03-21  53.28  34.90  41.88  60.4500  29.44  50.48  36.95  152.540
2017-03-22  52.79  33.35  39.78  59.5500  28.23  48.02  35.75  151.600
2017-03-23  53.04  33.41  40.70  57.6500  28.58  52.90  35.60  151.270
2017-03-24  54.05  33.61  41.69  54.0000  28.62  51.78  36.50  150.780
2017-03-27  52.60  31.74  41.07  58.0900  28.12  53.84  35.70  148.500
2017-03-28  53.29  32.50  41.83  60.7500  28.72  60.02  34.90  147.190
2017-03-29  53.26  32.91  42.69  67.9000  28.99  59.18  34.70  148.380
2017-03-30  53.06  33.00  41.85  67.4000  29.19  58.07  35.00  149.240
2017-03-31  53.07  34.06  42.37  73.0135  29.82  55.35  35.20  148.260
2017-04-03  52.90  34.62  42.33  75.2000  29.75  56.92  35.30  148.400
2017-04-04  53.20  34.03  42.09  71.8500  29.25  53.21  34.30  144.930
2017-04-05  52.72  34.79  41.15  67.4000  29.58  51.30  34.90  143.760
2017-04-06  52.70  33.85  41.40  65.9500  29.79  44.76  34.25  143.750
2017-04-07  53.07  33.25  41.53  64.9500  30.03  46.00  34.30  142.510
2017-04-10  52.90  33.66  41.81  66.7000  30.77  45.32  34.30  141.880
...           ...    ...    ...      ...    ...    ...    ...      ...
2018-01-17  71.72  56.03  58.31  71.5010  41.48  34.00  36.30  114.740
2018-01-18  72.20  53.67  58.00  71.5010  40.42  33.73  36.25  115.670
2018-01-19  72.48  52.86  58.59      NaN  40.60  34.87  36.10  116.240
2018-01-22  73.17  52.80  57.99  69.4000  42.08  34.98  37.20  116.880
2018-01-23  74.05  52.34  57.74  67.7000  42.30  34.42  36.30  117.740
2018-01-24  73.66  52.90  54.35  69.6500  41.19  34.92  36.20  119.260
2018-01-25  74.17  53.74  54.00  69.6647  41.80  34.32  36.10  121.120
2018-01-26  74.30  53.55  53.65  67.9000  41.86  34.91  36.20  123.340
2018-01-29  74.48  53.89  52.79  68.1500  42.50  34.63  36.10  123.520
2018-01-30  73.99  53.67  52.45  66.9500  41.39  32.74  36.00  121.570
2018-01-31  73.77  52.75  53.08  69.0241  42.13  33.01  36.20  119.860
2018-02-01  73.18  51.41  54.00  66.6000  40.76  32.50  36.25  116.240
2018-02-02  72.32  52.00  53.49  67.7000  40.53  33.61  35.95  115.920
2018-02-05  70.86  48.61  51.99  67.7000  38.71  32.50  35.40  113.050
2018-02-06  66.96  47.44  49.32  67.7000  36.67  32.00  33.40  108.280
2018-02-07  68.19  49.23  50.91  67.7000  38.37  33.86  33.55  112.090
2018-02-08  68.09  47.81  51.44  69.6500  39.49  31.30  33.70  109.930
2018-02-09  66.40  46.54  49.70  67.6000  38.67  32.18  33.45  110.390
2018-02-12  67.46  46.05  48.79  67.2000  39.53  30.77  33.30  109.795
2018-02-13  67.97  46.39  49.70  67.2000  39.41  29.30  33.45  109.170
2018-02-14  67.80  46.71  50.24  65.3000  39.04  29.10  33.55  105.500
2018-02-15  74.94  48.99  51.45  64.0000  45.92  31.28  34.60  109.230
2018-02-16  71.97  47.50  51.80      NaN  44.22  31.63  34.45  108.720
2018-02-20  71.50  46.84  51.23  64.2000  43.50  32.20  34.85  107.400
2018-02-21  71.12  48.21  51.96      NaN  42.40  33.66  34.40  116.960
2018-02-22  71.72  48.01  53.24  67.0000  43.89  28.66  34.65  115.100
2018-02-23  71.15  48.06  53.30  67.0000  44.43  27.00  35.10  111.150
2018-02-26  71.00  47.42  53.99  68.0000  45.15  28.06  35.40  116.500
2018-02-27  70.75  46.50  54.89  68.0000  45.47  28.00  35.65  113.260
2018-02-28  69.42  46.25  54.41  68.0000  46.12  27.57  38.65  110.710

                            ...    adj_close                                  \
ticker         AAPL    AAT  ...         ZEUS   ZGNX       ZION   ZIOP   ZIXI
date                        ...
2017-02-28  137.080  44.48  ...    24.124440  10.35  44.692993  6.350  5.010
2017-03-01  137.890  43.97  ...    25.880395  10.35  46.315478  6.370  5.140
2017-03-02  140.000  43.56  ...    23.785221  10.10  44.752716  6.310  5.190
2017-03-03  138.780  43.24  ...    23.406094   9.90  45.150872  6.480  5.150
2017-03-06  139.365  42.84  ...    21.729954   9.65  45.121011  6.510  5.060
2017-03-07  139.060  42.61  ...    20.612528   9.40  45.071241  6.360  5.110
2017-03-08  138.950  42.03  ...    20.013906   9.40  45.051333  6.380  5.080
2017-03-09  138.740  41.58  ...    19.275607   9.55  45.071241  6.390  5.100
2017-03-10  139.250  41.23  ...    19.175837  10.80  44.702947  6.890  5.020
2017-03-13  138.850  41.52  ...    19.944067  10.25  44.822394  6.470  4.870
2017-03-14  139.300  41.42  ...    20.782137  10.20  44.284883  6.280  4.870
2017-03-15  139.410  41.92  ...    20.911838  10.70  43.866820  6.410  4.830
2017-03-16  140.720  42.62  ...    21.719977  11.00  44.155483  6.490  5.230
2017-03-17  141.000  42.91  ...    22.198874  10.70  43.558249  6.350  5.070
2017-03-20  140.400  42.45  ...    20.961724  10.55  42.990877  6.240  4.940
2017-03-21  142.110  42.24  ...    19.465170  10.35  40.651711  5.870  4.760
2017-03-22  139.845  41.76  ...    19.175837  10.35  40.542218  5.810  4.680
2017-03-23  141.260  41.13  ...    19.285584  10.40  40.701481  5.870  4.620
2017-03-24  141.500  42.05  ...    18.671997  10.45  40.721389  5.880  4.630
2017-03-27  139.390  41.61  ...    18.756802  10.90  40.591988  6.690  4.680
2017-03-28  140.910  41.41  ...    18.726871  10.75  41.109591  6.620  4.690
2017-03-29  143.680  41.32  ...    18.637077  11.25  41.129498  6.690  4.680
2017-03-30  144.190  41.24  ...    18.557261  10.75  42.184611  6.450  4.740
2017-03-31  143.720  41.49  ...    18.517353  10.85  41.806363  6.340  4.810
2017-04-03  143.710  41.79  ...    18.587192  10.65  41.577424  6.300  4.760
2017-04-04  143.250  41.79  ...    19.195791  10.30  41.467931  6.320  4.780
2017-04-05  144.220  41.84  ...    18.277905  10.30  40.860743  6.260  4.770
2017-04-06  144.290  41.43  ...    18.168157  10.45  41.308668  6.130  4.810
2017-04-07  143.730  42.01  ...    19.295561  10.70  41.328576  6.240  4.940
2017-04-10  143.600  41.86  ...    18.587192  10.60  40.741296  6.590  5.050
...             ...    ...  ...          ...    ...        ...    ...    ...
2018-01-17  176.150  36.18  ...    24.580000  35.45  53.320000  4.350  4.520
2018-01-18  179.370  36.27  ...    23.930000  35.30  52.860000  4.360  4.520
2018-01-19  178.610  35.73  ...    24.060000  35.95  53.730000  4.280  4.650
2018-01-22  177.300  36.22  ...    24.430000  37.60  54.160000  5.140  4.470
2018-01-23  177.300  36.40  ...    24.310000  38.15  54.170000  4.890  4.550
2018-01-24  177.250  36.61  ...    24.480000  37.40  53.740000  4.610  4.350
2018-01-25  174.505  36.24  ...    25.120000  37.05  53.020000  4.720  4.350
2018-01-26  172.000  36.25  ...    24.810000  37.95  54.020000  4.610  4.280
2018-01-29  170.160  35.63  ...    24.160000  37.95  54.190000  4.460  4.270
2018-01-30  165.525  34.90  ...    23.370000  37.20  53.930000  4.200  4.280
2018-01-31  166.870  34.99  ...    23.310000  36.30  54.030000  3.945  4.230
2018-02-01  167.165  35.25  ...    23.610000  38.00  54.980000  3.820  4.220
2018-02-02  166.000  34.35  ...    22.350000  37.00  54.160000  3.700  4.050
2018-02-05  159.100  34.18  ...    21.339900  35.80  51.920000  3.470  3.970
2018-02-06  154.830  32.76  ...    21.340000  38.70  52.520000  4.010  4.000
2018-02-07  163.085  32.83  ...    21.590000  38.80  54.020000  4.110  4.080
2018-02-08  160.290  32.82  ...    21.600000  37.45  50.710000  3.870  4.065
2018-02-09  157.070  32.17  ...    21.770000  37.80  51.620000  3.890  4.140
2018-02-12  158.500  32.96  ...    22.580000  38.10  52.060000  3.940  4.030
2018-02-13  161.950  32.54  ...    23.350000  38.05  51.960000  3.920  4.050
2018-02-14  163.045  32.17  ...    23.800000  38.95  54.510000  3.940  4.090
2018-02-15  169.790  32.07  ...    23.820000  41.35  54.750000  3.880  4.160
2018-02-16  172.360  32.12  ...    24.470000  41.25  55.070000  3.830  4.160
2018-02-20  172.050  32.46  ...    24.600000  41.85  54.970000  3.680  4.100
2018-02-21  172.830  32.06  ...    24.480000  43.00  55.860000  3.730  4.130
2018-02-22  171.800  32.50  ...    23.330000  43.20  54.720000  3.710  4.100
2018-02-23  173.670  32.79  ...    24.110000  43.45  55.680000  3.870  3.900
2018-02-26  176.350  33.00  ...    23.790000  44.45  56.290000  3.830  4.040
2018-02-27  179.100  32.94  ...    23.540000  44.00  55.740000  3.740  4.050
2018-02-28  179.260  31.87  ...    22.530000  42.40  54.970000  3.730  4.050


ticker        ZLTQ   ZNGA   ZOES        ZTS   ZUMZ
date
2017-02-28  55.360  2.650  17.92  53.113886  20.40
2017-03-01  55.480  2.710  17.88  53.691753  20.00
2017-03-02  55.540  2.740  17.44  53.173666  21.10
2017-03-03  55.680  2.780  17.01  53.223482  20.75
2017-03-06  55.550  2.750  17.38  52.884732  21.15
2017-03-07  55.400  2.740  16.96  52.874769  20.80
2017-03-08  55.520  2.740  17.41  52.805027  21.25
2017-03-09  55.600  2.750  17.02  53.492488  21.00
2017-03-10  55.890  2.820  17.26  53.143776  18.40
2017-03-13  55.615  2.810  16.93  53.362967  17.70
2017-03-14  55.630  2.780  16.67  53.223482  17.65
2017-03-15  55.790  2.840  16.86  54.080318  17.65
2017-03-16  55.630  2.840  17.37  54.229766  17.80
2017-03-17  55.880  2.800  16.66  53.801348  17.95
2017-03-20  55.790  2.800  16.69  54.080318  17.45
2017-03-21  55.530  2.760  17.03  53.193592  17.10
2017-03-22  55.500  2.760  17.08  53.671826  16.75
2017-03-23  55.620  2.810  17.04  53.602084  17.30
2017-03-24  55.800  2.800  17.04  53.651900  17.20
2017-03-27  55.780  2.810  17.35  53.771458  17.35
2017-03-28  55.840  2.820  17.87  53.960759  17.75
2017-03-29  55.690  2.830  18.52  53.622010  18.25
2017-03-30  55.770  2.880  18.32  53.273298  18.40
2017-03-31  55.610  2.850  18.50  53.173666  18.30
2017-04-03  55.660  2.830  17.64  52.974401  17.35
2017-04-04  55.620  2.790  16.96  52.560928  16.75
2017-04-05  55.650  2.780  17.03  52.580894  16.10
2017-04-06  56.440  2.800  17.33  52.580894  16.80
2017-04-07  56.420  2.800  17.09  52.451114  16.80
2017-04-10  56.430  2.790  17.44  52.650776  17.10
...            ...    ...    ...        ...    ...
2018-01-17     NaN  3.800  15.20  76.770000  22.45
2018-01-18     NaN  3.750  15.05  76.330000  22.40
2018-01-19     NaN  3.720  15.52  76.620000  23.10
2018-01-22     NaN  3.730  15.32  77.480000  23.55
2018-01-23     NaN  3.720  15.31  77.590000  22.60
2018-01-24     NaN  3.650  14.87  78.330000  22.40
2018-01-25     NaN  3.690  14.78  79.250000  22.35
2018-01-26     NaN  3.730  14.20  80.090000  22.35
2018-01-29     NaN  3.670  14.37  79.180000  22.35
2018-01-30     NaN  3.600  14.58  78.350000  21.35
2018-01-31     NaN  3.585  14.72  76.730000  20.75
2018-02-01     NaN  3.685  14.47  77.820000  20.85
2018-02-02     NaN  3.610  13.87  76.780000  20.60
2018-02-05     NaN  3.515  13.75  73.830000  20.40
2018-02-06     NaN  3.555  13.60  73.270000  20.55
2018-02-07     NaN  3.690  13.73  73.860000  20.45
2018-02-08     NaN  3.480  13.57  71.510000  20.10
2018-02-09     NaN  3.305  13.43  72.350000  19.30
2018-02-12     NaN  3.420  13.75  73.190000  18.95
2018-02-13     NaN  3.440  13.67  73.240000  19.20
2018-02-14     NaN  3.490  13.84  74.460000  20.25
2018-02-15     NaN  3.570  14.05  78.500000  20.10
2018-02-16     NaN  3.590  13.90  79.730000  20.10
2018-02-20     NaN  3.570  13.71  80.350000  19.30
2018-02-21     NaN  3.560  13.34  80.500000  19.50
2018-02-22     NaN  3.510  14.27  80.760000  19.80
2018-02-23     NaN  3.600  14.78  82.790000  20.25
2018-02-26     NaN  3.610  15.36  83.300000  20.55
2018-02-27     NaN  3.500  15.30  81.670000  19.80
2018-02-28     NaN  3.460  14.88  80.860000  19.70

[253 rows x 5302 columns]